### ISSUE TITLE
`changeset publish` fails with `Unexpected end of JSON input` after package deletion

### ISSUE THREAD

**Issue by sgoll** [atlassian/changesets#338]
## Affected Packages

`@changesets/cli@2.6.5`

## Problem

We are using `changeset publish` for packages hosted at our organization's GitHub package registry. After deleting a specific package version (the package itself still exists), `changeset publish` fails with the following error:

```
🦋  error SyntaxError: Unexpected end of JSON input
🦋  error     at JSON.parse (<anonymous>)
🦋  error     at npmRequestLimit (…/node_modules/@changesets/cli/dist/cli.cjs.dev.js:505:17)
🦋  error     at process._tickCallback (internal/process/next_tick.js:68:7)
```

## Proposed solution

`changeset publish` should handle package deletion (as in deleting a single package version) gracefully.

**Comment by Andarist** [comment]
The error seems to be coming from here:
https://github.com/atlassian/changesets/blob/d570a24740a374a9547dd7d931e6ac854e36a9fb/packages/cli/src/commands/publish/npm-utils.ts#L61

This should just check the package name (so removing a particular version shouldn't matter) and it also shouldn't crash on non-existing packages as receiving errors here is explicitly allowed and handled here:
https://github.com/atlassian/changesets/blob/d570a24740a374a9547dd7d931e6ac854e36a9fb/packages/cli/src/commands/publish/npm-utils.ts#L66-L67

I've encountered this problem in the past when one of my dependencies had old `npm` as its dependency and changesets have tried to use it (instead of the global one) but that old version had no support for `info` cmd. Could you check if that's maybe your problem as well?

**Comment by sgoll** [comment]
@Andarist It seems that GitHub returns invalid data when a package version has been removed.

For any package,`npm info --json (…)` returns the correct data. But for the broken package in question (where the most recent version has been yanked from the registry), the output of `npm info` is just the empty string (no error, no contents).

Has anybody experienced this problem?

**Comment by Andarist** [comment]
Huh, that's weird - maybe worth reporting to npm itself? If that's the case I guess changesets should implement a workaround for this issue.

**Comment by talentlessguy** [comment]
Same issue with `pnpm`:

```
➜ pnpx changeset publish
🦋  info npm info @tinyhttp/app
🦋  info npm info @tinyhttp/cors
🦋  info npm info @tinyhttp/etag
🦋  info npm info @tinyhttp/logger
🦋  info npm info @tinyhttp/static
🦋  info @tinyhttp/app is being published because our local version (0.1.20) has not been published on npm
🦋  info @tinyhttp/cors is being published because our local version (0.1.20) has not been published on npm
🦋  info @tinyhttp/etag is being published because our local version (0.1.20) has not been published on npm
🦋  info @tinyhttp/logger is being published because our local version (0.1.20) has not been published on npm
🦋  info @tinyhttp/static is being published because our local version (0.1.20) has not been published on npm
🦋  info Publishing "@tinyhttp/app" at "0.1.20"
🦋  info Publishing "@tinyhttp/cors" at "0.1.20"
🦋  info Publishing "@tinyhttp/etag" at "0.1.20"
🦋  info Publishing "@tinyhttp/logger" at "0.1.20"
🦋  info Publishing "@tinyhttp/static" at "0.1.20"
🦋  error SyntaxError: Unexpected end of JSON input
🦋  error     at JSON.parse (<anonymous>)
🦋  error     at internalPublish (/home/v1rtl/Coding/tinyhttp/node_modules/.pnpm/@changesets/cli@2.9.1_@types+node@14.0.13/node_modules/@changesets/cli/dist/cli.cjs.dev.js:591:19)
🦋  error     at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

reproduction repo: https://github.com/talentlessguy/tinyhttp

**Comment by camdub** [comment]
Seeing the same issue @sgoll pointed out, but in my case it was for an unpublished package. Github registry returns an empty string instead of a 404 like npm. Opened a PR to hopefully move towards a solution on this.

**Comment by steve-taylor** [comment]
Still an issue. I have a package that was accidentally set to `"private": true`. I removed `"private": true` from its package.json, added a changeset, run `changeset version`, then pushed to origin. When the pipeline ran `changeset publish`, it tried to `PUT` the package instead of `POST` it because it assumed it already exists despite earlier attempting to fetch it and getting 404.

**Comment by Andarist** [comment]
@steve-taylor @codingwithchris could you describe your issues step by step so I could get a proper bird's eye view of everything involved?
