### ISSUE TITLE
Outdated octokit dependency

### ISSUE THREAD

**Issue by maraisr** [atlassian/changesets#405]
## Problem

My builds are failing this morning to what I can only perceive as as an action bug?

```
Deprecation: [@octokit/request-error] `error.code` is deprecated, use `error.status`.
    at o.get (/home/runner/work/_actions/changesets/action/master/dist/index.js:94:444)
    at f (/home/runner/work/_actions/changesets/action/master/dist/index.js:1444:1696)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  name: 'Deprecation'
}
o [HttpError]: Validation Failed
##[error]Validation Failed
```

> https://github.com/autoguru-au/overdrive/runs/828749495?check_suite_focus=true#step:7:41

## Proposed solution

Not too sure, this could be unrelated.

**Comment by Andarist** [comment]
Seems like GitHub has made a breaking change somewhere but they have already corrected it (?). Not sure why this would happen - it would mean the broken client-server contract because client dependencies are all bundled in for `@changesets/action` so they could have not changed without us upgrading them. 

I've just tried releasing with the action and it has succeeded - https://github.com/atlassian/changesets/runs/830527350 . Could you maybe rerun your job? I will take a close eye on this one nevertheless and update Octokit dependencies soon.

**Comment by maraisr** [comment]
Thanks for this @Andarist I don't think it works. I've tried re-running the builds, pushed new commits etc.. All still broken.

https://github.com/autoguru-au/overdrive/runs/839983903#step:7:41

![image](https://user-images.githubusercontent.com/599459/86554567-59719300-bf91-11ea-9579-245dce81e68a.png)

The action runs its own copy of node_modules yeah? I only ask, because I cache node_modules between runs. Perhaps there is an issue there?

**Comment by Andarist** [comment]
> The action runs its own copy of node_modules yeah?

We prepare a bundle with Parcel which bundles required node_modules into it - so there is 0 chance of code dependencies being altered without us running a build script again.

> I only ask, because I cache node_modules between runs.

So any extra caching like this shouldn't affect us in any way.

---

I'll proceed with updating Octokit soon to see if this resolves your issue - I will let you know once I do this.

**Comment by maraisr** [comment]
I feel this closing of this ticket was a bit premature @mitchellhamilton... Post that merge I have reran our release's, and none seem to succeed.

https://github.com/autoguru-au/overdrive/runs/841216184#step:7:41

**Comment by Andarist** [comment]
This was automatically closed when the other PR got merged in. 

Thanks for checking it out though - now I know that I will have to dig deeper into your case to see what's going on.

**Comment by Andarist** [comment]
@maraisr I'm pretty sure that I know what's wrong. It's a regression from https://github.com/changesets/action/pull/35 . Gonna fix this most likely tomorrow.

**Comment by maraisr** [comment]
Thank you so much for your continued efforts here @Andarist ❤️ I appreciate you

**Comment by maraisr** [comment]
Thank you so much @Andarist! I ran my builds this morning, and they all passed 100% okay. It all works now, thank you again so much for your continued support and dedication to this cause!
