### ISSUE TITLE
internalPublish fails with no console output if access is set to restricted

### ISSUE THREAD

**Issue by andrico1234** [atlassian/changesets#599]
## Affected Packages

@changesets/cli

## Problem

This is completely my fault for not reading the config docs properly, but I overlooked setting my `access` field to `public` and left it ad the default `restricted` value. 

When I then tried to publish my changes for the first time, I got a generic error:

```
error parsing json: 
🦋  error SyntaxError: Unexpected end of JSON input
🦋  error     at JSON.parse (<anonymous>)
🦋  error     at jsonParse (locationy/node_modules/@changesets/cli/dist/cli.cjs.dev.js:584:17)
🦋  error     at internalPublish (/location/@changesets/cli/dist/cli.cjs.dev.js:754:14)
```

After a little digging it looked like this was because the following code was returning undefined:

```
  let {
    stdout
  } = await spawn__default['default'](publishTool.name, ["publish", opts.cwd, "--json", ...publishFlags], {
    env: Object.assign({}, process.env, envOverride)
  });
```

After running the `npm publish ${cwd} --json`, i got the following output

```
npm ERR! code E402
npm ERR! 402 Payment Required - PUT https://registry.npmjs.org/@repo/packages - You must sign up for private packages
{
  "error": {
    "code": "E402",
    "summary": "402 Payment Required - PUT https://registry.npmjs.org/@repo%2fpackage - You must sign up for private packages",
    "detail": ""
  }
}
```

## Proposed solution

It would be very useful to have this logged out:

a) because I imagine I'm not the first person to maybe have missed some of the details in the docs
b) if someone wanted to publish their packages privately, but had something misconfigured in their NPM, they wouldn't get any feedback

**Comment by andrico1234** [comment]
This was actually because I hadn't created an initial scope for my package, which is config I needed to do in NPM. I'm not sure how changesets would communicate this, because it required digging in the NPM logs to understand whatthe problem was, so I'm going to close this!
